package com.springboot.elasticbeanstalk.com.springbootEBS.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "person")
public class Person implements Serializable {

    @DynamoDBHashKey (attributeName = "personId")
    @DynamoDBAutoGeneratedKey
    private String personId;
    private String name;
    private int age;
    private String email;
    private Address address;
}
